### PR TITLE
use write for (buffered) stdout/stderr appender

### PR DESCRIPTION
**Pull request by kares**
would like to change `syswrite` to `write` for STDOUT/STDERR, these are already sync-ed and OS consoles should know what to do best. current impl leads to warnings in real-world usage e.g. on Linux: 
```
[2016-01-28 13:56:24.939] DEBUG Punchblock::Connection::Asterisk: Starting up...
/opt/local/rvm/gems/jruby-1.7.23@global/gems/logging-2.0.0/lib/logging/appenders/io.rb:74 warning: syswrite for buffered IO
[2016-01-28 13:56:24.957] INFO  Ifbyphone::Plugin: Ifbyphone plugin has been loaded
[2016-01-28 13:56:24.958] INFO  Ifbyphone::Plugin: Ifbyphone plugin has been loaded
/opt/local/rvm/gems/jruby-1.7.23@global/gems/logging-2.0.0/lib/logging/appenders/io.rb:74 warning: syswrite for buffered IO
[2016-01-28 13:56:24.962] INFO  Adhearsion::PunchblockPlugin::Initializer: Starting connection to server
[2016-01-28 13:56:24.967] ERROR Punchblock::Connection::Asterisk: Connection failed due to Errno::ECONNREFUSED. Check your config and the server.
/opt/local/rvm/gems/jruby-1.7.23@global/gems/logging-2.0.0/lib/logging/appenders/io.rb:74 warning: syswrite for buffered IO
```

there's some duplicity with the commit - introducing a shared `Appender::Console` mixin might help.

there's some minor additional commits. reproducing for a test-case is not easy since there would need to be quite some logging going on against the stream.

### CODE REVIEW

**Comment by TwP** [comment]
> would like to change syswrite to write for STDOUT/STDERR, these are already sync-ed and OS consoles should know what to do best

Using ruby 2.1.6 on a mac ...

```sh
> ruby -e 'puts $stdout.sync'
false
```

It is my understanding that STDOUT and STDERR are buffered by default in Ruby. That is why the IO appender in the Logging framework sets the `sync` flag to `true` - see https://github.com/TwP/logging/blob/master/lib/logging/appenders/io.rb#L36

Could you provide a simple example that produces this `syswrite for buffered IO` warning?

**Comment by thedrow** [comment]
@TwP is correct. Sync is set to false for STDOUT/STDERR.

**Comment by kares** [comment]
> @TwP is correct. Sync is set to false for STDOUT/STDERR.
>> would like to change syswrite to write for STDOUT/STDERR, these are already sync-ed and OS consoles should know what to do best. current impl leads to warnings in real-world usage e.g. on Linux

sorry, meant that it is always forced to `sync = true` by Logging thus it should be fine to just use `write` (most logger libraries seem to use write) esp. as there's potential warnings [coming of syswrite](https://github.com/ruby/ruby/blob/ruby_2_3/io.c#L4656) e.g. if the buffer wasn't empty? 

seems I will need to look into this more as its proving hard to reproduce in isolation - current theory is that there needs to be multiple threads using STDOUT or someone else doing "plain" `write` as well (which is not uncommon for an std-out)

**Comment by kares** [comment]
a minimal reproduction case would be : 
```ruby
STDOUT.print ' '; STDOUT.putc ' '

require 'logging'
require 'logging/appenders'

Logging.logger.root.appenders = Logging::Appenders.stdout

logger = Logging::Logger['sample']
logger.level = :debug
logger.info "hello!"
```
... this will of course work on MRI 2.x and on latest JRuby 9K but reproduces the warning with 1.7.x : 
```
  ~/logging/lib/logging/appenders/console.rb:47 warning: syswrite for buffered IO
 INFO  sample : hello!
```
the reason it works in latest JRuby is due mostly a one-to-one **io.c** code conversion to Java, while in 1.7.x the IO sub-system wasn't sharing the exact same logic.

still believe the warning is legitimate in this case and just so it does not appear in recent versions is an impl detail. mixing `syswrite` with "buffered" writes is not a good idea and for streams such as `STDOUT` its non-sense to expect that no one else will `write` to the stream e.g. using `puts` or Ruby's `warn`. and someone else might even mess with flipping `sync` over.

`syswrite` is perfectly fine for File/Socket appenders where no one else is ever expected to be using the same `IO`. changing common std `IO` to a plain `write` eliminates all headaches while still does the same (non-buffering by default) since `sync` is being set, did I miss anything?

**Comment by TwP** [comment]
> changing common std `IO` to a plain `write` eliminates all headaches while still does the same (non-buffering by default) since `sync` is being set, did I miss anything?

That does sound correct, and nothing appears to be missing. Let me look at this implementation a bit this weekend.

It would be much cleaner to create a single `Console` appender that implements the changes to `canonical_write`. The `Stdout` and `Stderr` appenders then become aliases for this `Console` appender class. I'll give this approach a shot and see how it goes.

**Comment by kares** [comment]
@TwP great, thanks. also did numbers on using `syswrite` vs sync-ed `write` with STDOUT appender. both MRI and JRuby performed roughly the same on both.

**Pull request merged**
