### PR TITLE
Fix issue 120 rails logging

### LINKED ISSUE #120: Rails.logger.extend(ActiveSupport::Logger.broadcast(log)) only works with blocks
```
log = Logging.logger['my logger']
log.add_appenders( Logging.appenders.stdout )
log.level = :info

log.info "going direct to logger"
>> INFO  my logger : going direct to logger

Rails.logger.extend(ActiveSupport::Logger.broadcast(log))

Rails.logger.info "without a block"
>> INFO  my logger : <NilClass> nil

Rails.logger.info { "within a block" }
>> INFO  my logger : within a block
```

I'd prefer to Rails.logger because I have other loggers attached (e.g. Loggly). But when doing so, the logging gem only works when the log message is wrapped in a block.

### PR DESCRIPTION
**Pull request by noahsw**
Fixes #120 

A more realistic test case would have tested Rails.logger.extend but I didn't want to add Rails as a dependency to the logging gem. So I just mimicked the contract that Rails.logger expects.

### CODE REVIEW

**Comment by thedrow** [comment]
What's the status here? Why is this not merged? Can I help?

**Comment by thedrow** [comment]
@TwP ping?

**Comment by TwP** [comment]
Thank you for the ping! My notifications settings are somewhat troublesome, and I've been missing PRs that people have opened. Thank you for opening this up. I'll take a look this evening while sitting on my couch at home watching Mythbusters with the wife.

A cursory glance looks good. The only thing I need to investigate a little bit more is the choice to **not** invoke the block if `data` has been provided. Currently the value returned from the block will supersede whatever is passed in as the `data`. This PR changes that precedence. It's an edge case and should be fine, but I'd like to double check.

**Comment by thedrow** [comment]
Can you please release a new version with this fix?

**Pull request merged**
