### PR TITLE
Enable asynchronous writes of the log buffer

### PR DESCRIPTION
**Pull request by TwP**
These changes enable the existing periodic flushing mechanism to be used to asynchronously write the log buffer to the IO stream. By setting the `async` flag to true, the flusher Thread will be used to write messages thereby freeing up the main program thread to continue on doing other work.

refs #130 

/cc @thedrow

### CODE REVIEW

**Comment by thedrow** [comment]
LGTM.
Did you benchmark the change?

**Comment by TwP** [comment]
@thedrow I took your `benchmark.rb` script changes and incorporated them into this PR. Here is the section comparing sync / async performance:

```
== File ==
                           user     system      total        real
Logging (Async):       4.280000   0.050000   4.330000 (  4.325593)
Logging (Sync):        4.410000   0.210000   4.620000 (  4.601383)
```

So asynchronous writes do yield a performance advantage here. Thank you for prodding this along :bow:

**Comment by thedrow** [comment]
Wonderful! Any chance to get this released?

**Comment by thedrow** [comment]
Any chance to get a new release with this change?

**Comment by TwP** [comment]
> Any chance to get a new release with this change?

The plan is to cut a new release towards the end of the month. Currently working on a few other changes in conjunction with some other developers. My apologies that this takes so long :disappointed:. Family, friends, health, job, and open source ... it is usually the open source that gets neglected.

**Comment by TwP** [comment]
@thedrow just release Logging v2.1.0 with these changes.

**Comment by thedrow** [comment]
Thanks!

**Pull request merged**
