### PR TITLE
File rolling is now synchronized

### PR DESCRIPTION
**Pull request by lzap**
File rolling is not synchronized, symptoms are that after rolling appender performs rotation it no longers writes any events and logging stack cease operations. The easiest reproducer:

```ruby
require './lib/logging'

$log = Logging.logger['example']
$log.add_appenders(Logging.appenders.rolling_file('/tmp/rolling.log', keep: 3, size: 500, age: 2))
$log.level = :debug

(1..30).each {
  Thread.new do
    (1..1000).each {
      $log.debug "a very nice little debug message #{Time.now}"
      $log.warn "this is your last warning"
    }
  end
}

sleep 10
```

Run it while watching digest of files:

    watch -n1 crc32 /tmp/rolling*

After two seconds thank to a race condition rotation is preformed incorrectly and events are not being written anymore therefore digest stop changing. With my patch, rotations are performed until all threads finish writing (about 10 seconds on my system - I was lazy to do thread joins).

In the patch, I am using the main mutex, however probably separate mutex dedicated for rotation could be used. Honestly I am not sure so I am going for safety first.

Edit: The reason why the stack stops logging is because there is an exception thrown:

```
No such file or directory @ rb_file_s_rename - (/tmp/test.log._copy_, /tmp/test.20190514-155314.log)
/home/lzap/work/logging/lib/logging/appenders/rolling_file.rb:409:in `rename'
/home/lzap/work/logging/lib/logging/appenders/rolling_file.rb:409:in `roll_by_date'
/home/lzap/work/logging/lib/logging/appenders/rolling_file.rb:351:in `roll_files'
/home/lzap/work/logging/lib/logging/appenders/rolling_file.rb:166:in `block in canonical_write'
/home/lzap/work/logging/lib/logging/utils.rb:88:in `flock?'
/home/lzap/work/logging/lib/logging/appenders/rolling_file.rb:162:in `canonical_write'
/home/lzap/work/logging/lib/logging/appenders/buffering.rb:285:in `write'
/home/lzap/work/logging/lib/logging/appender.rb:81:in `append'
/home/lzap/work/logging/lib/logging/logger.rb:397:in `block in log_event'
/home/lzap/work/logging/lib/logging/logger.rb:397:in `each'
/home/lzap/work/logging/lib/logging/logger.rb:397:in `log_event'
/home/lzap/work/logging/lib/logging/logger.rb:102:in `info'
```

I still need to understand why this happened, my patch might not be actually correct.

### CODE REVIEW

**Comment by lzap** [comment]
After some more time spent on this, I believe that locking is not right for both file and rolling file appenders. Here is some info on how/why Ruby has implemented combination of mutex and flock approach:

https://www.slideshare.net/sonots/rubylogger-rubyconf-20131109

Basically `write`, `close` and `reopen` all use mutex and on top of that rolling uses flock on non-Windows platforms. No LOCK_SH is used at all. It also uses `O_EXCL` for reliable log file creation.

https://github.com/ruby/ruby/blob/trunk/lib/logger.rb

The mechanism of setting level to `:off` when exception happens is quite annoying - I've spend three days haunting this bug. We are experiencing issues with both file rolling and also file reopening when using normal (regular) file logger (write to closed device).

**Comment by TwP** [comment]
Thank you for your example code in the PR body here - there is definitely a bug in the rolling appender that will cause multiple threads to simultaneously roll the log files. I've confirmed locally that your fix does work.

I'm reading through the core Ruby Logger code to understand how @sonots tackled this problem. I'll work on this today and attempt to make something that works correctly.

>  The mechanism of setting level to :off when exception happens is quite annoying - I've spend three days haunting this bug.

I'm so sorry. There is a new setting

```ruby
Logging.raise_errors = true
```

that will for exceptions to be raised to the calling code if an internal Logging error occurs. It defaults to `false`, but you can set it to `true` to help with your debugging efforts. This feature will be included in the next gem release.

**Comment by lzap** [comment]
Don't apologize, we are hackers in the end. This gave me the opportunity to understand logging little bit more ;-)

Let me know when you have something, I'd love to test it. Cheers!

**Comment by lzap** [comment]
Hello there, was this bug already fixed elsewhere?

**Comment by lzap** [comment]
Just wanted to know if you are planning any short-term changes in this regard. I have a blocked patch in our project as we use file rolling for development environment and if you can confirm I'd either wait for a definitive solution or we would probably remove logging-based file rolling completely. Thanks, take care!

**Comment by TwP** [comment]
I have a long weekend and nowhere to go :smile_cat:. Let me go back and look at my notes and get this fixed for you.

**Comment by TwP** [comment]
Closing this out in favor of #216

**Pull request closed without merging**
